# Replace the SECTIONS list (around line 20) with this:
SECTIONS = [
    ("01-Project-Files", "📦 Project Files"),
    ("02_Docker_Commands", "🐳 Docker Commands"),
    ("03_Docker_Files", "🐳 Docker Files"),
    ("04_Docker_Compose", "🐳 Docker Compose"),
    ("05_Docker_Buildx", "🐳 Docker Buildx"),
    ("06_Terraform_Basics", "🏗️ Terraform Basics"),
    ("07_Terraform_EKS_Cluster", "☸️ Terraform EKS Cluster"),
    ("08_Kubernetes_Foundation", "☸️ Kubernetes Foundation"),
    ("09_Kubernetes_Secrets", "🔐 Kubernetes Secrets"),
    ("10_Kubernetes_Storage", "💾 Kubernetes Storage"),
    ("11_Kubernetes_Ingress", "🚪 Kubernetes Ingress"),
    ("12_Helm", "⎈ Helm"),
    ("13_Terraform_EKS_Cluster_with_AddOns", "☸️ Terraform EKS with AddOns"),
    ("14_RetailStore_Microservices_with_AWS_Data_Plane", "🛒 RetailStore with AWS Data Plane"),
    ("15_Terraform_EKS_Cluster_ExternalDNS", "🌍 Terraform EKS with External DNS"),
    ("16_RetailStore_Microservices_ExternalDNS", "🛒 RetailStore with External DNS"),
    ("17_Autoscaling_Karpenter", "⚡ Autoscaling - Karpenter"),
    ("18_Autoscaling_HPA", "📈 Autoscaling - HPA"),
    ("19_Helm_RetailStore_AWS_Dataplane", "⎈ Helm RetailStore with AWS Data Plane"),
    ("20_Observability_OpenTelemetry", "👀 Observability - OpenTelemetry"),
    ("21_DevOps_CICD", "🚀 DevOps CI/CD"),
]